name: dollar_kursi
description: "A new Flutter project."
publish_to: "none"
version: 1.0.3+5

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  flutter_svg: ^2.0.5
  provider: ^6.0.5
  http: ^0.13.6
  hive: ^2.2.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.20.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^18.0.1
  get_it: ^9.0.5
  shared_preferences: ^2.5.3
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
